"""
Lightweight static verification for generated bpy scripts.

Since scripts are now deterministically generated by SceneBuilder,
this serves as a safety net rather than an LLM output validator.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import List


@dataclass
class VerificationResult:
    ok: bool
    notes: str


# bpy.ops calls that are allowed in generated scripts
_ALLOWED_OPS = {
    ("mesh", func)
    for func in [
        "primitive_cube_add",
        "primitive_uv_sphere_add",
        "primitive_ico_sphere_add",
        "primitive_cylinder_add",
        "primitive_cone_add",
        "primitive_plane_add",
        "primitive_torus_add",
        "primitive_grid_add",
        "primitive_circle_add",
        "primitive_monkey_add",
    ]
} | {
    ("object", "select_all"),
    ("object", "delete"),
    ("object", "modifier_apply"),
    ("object", "light_add"),
    ("object", "camera_add"),
    ("object", "empty_add"),
    ("object", "shade_smooth"),
    ("object", "shade_auto_smooth"),
    ("view3d", "view_selected"),
}


def verify_bpy_script(script: str) -> VerificationResult:
    s = script or ""
    findings: List[str] = []

    def require(snippet: str, msg: str):
        if snippet not in s:
            findings.append(msg)

    require("import bpy", "Missing `import bpy`.")
    require("try:", "Missing try/except wrapping.")
    require("except Exception", "Missing `except Exception` handler.")
    require("scene.unit_settings.scale_length", "Missing unit scale assignment.")
    require("def sanity_check", "Missing `sanity_check` function.")

    # Allow only whitelisted bpy.ops calls
    for match in re.finditer(r"bpy\.ops\.(\w+)\.(\w+)", s):
        module, func = match.group(1), match.group(2)
        if (module, func) not in _ALLOWED_OPS:
            findings.append(f"Uses `bpy.ops.{module}.{func}`; not in allowed ops list.")

    if len(s.strip()) < 50:
        findings.append("Script is suspiciously short (< 50 chars).")

    ok = len(findings) == 0
    notes = "OK" if ok else "\n".join(f"- {f}" for f in findings)
    return VerificationResult(ok=ok, notes=notes)
